import type { Metadata } from "next";
import ServerProtected from "@/components/ServerProtected";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <ServerProtected>{children}</ServerProtected>;
}
